# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "kbwapi"
main = "src/index.ts"
compatibility_date = "2025-03-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "<Kingdom-Beast-World>"
database_id = "cd100dce-750c-4f74-ad64-17cfb7c5d0d6"  #  reemplaza con tu ID real

[[secrets_store_secrets]]
binding = "ADMIN_TOKEN"
secret_name = "admin_token"
store_id = "bbfe8b921ab8493e989006835362bf8e"      #  opcional, puedes dejarlo fuera si usas el comando manualmente

[[secrets_store_secrets]]
binding = "USER_TOKEN"
secret_name = "user_token"
store_id = "bbfe8b921ab8493e989006835362bf8e"      #  opcional, puedes dejarlo fuera si usas el comando manualmente

[observability]
enabled = true