# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "kbwapi"
main = "src/index.ts"
compatibility_date = "2025-03-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "<Kingdom-Beast-World>"
database_id = "cd100dce-750c-4f74-ad64-17cfb7c5d0d6"  #  reemplaza con tu ID real

[[r2_buckets]]
binding = "R2_BUCKET"       # Este es el nombre que usar√°s en el Worker
bucket_name = "card-images" # El nombre real del bucket en R2
preview_bucket_name = "card-images"

[[secrets_store_secrets]]
binding = "ADMIN_TOKEN"
secret_name = "admin_token"
store_id = "bbfe8b921ab8493e989006835362bf8e"      #  opcional, puedes dejarlo fuera si usas el comando manualmente

[[secrets_store_secrets]]
binding = "USER_TOKEN"
secret_name = "user_token"
store_id = "bbfe8b921ab8493e989006835362bf8e"      #  opcional, puedes dejarlo fuera si usas el comando manualmente

[observability]
enabled = true

[vars]
PLAYFAB_TITLE_ID = "E50CF"
PLAYFAB_SECRET_KEY = "XTBM56IPCOYNJZYQAX6OYKOEOAX5ONPOONCDQNUA94UQZFI9ZN"
FIREBASE_API_KEY = "AIzaSyDGs_FsdfJ-bdNjyR_zO2y5D7UeL_qmXpw"